### ISSUE TITLE
AttributeError: module 'jaxlie.manifold' has no attribute 'zero_tangents'

### ISSUE THREAD

**Issue by mbenencase** [brentyi/jaxlie#5]
Hey, I was trying the example `se3_optimization.py`, I installed all the requirerd libraries, but when I ran the script I faced the issue bellow

```
(jax) mbenencase@mbenencase:~/projects/jaxlie$ python se3_optimization.py 
tangent_space
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "/home/mbenencase/projects/jaxlie/se3_optimization.py", line 246, in <module>
    dcargs.cli(main)
  File "/home/mbenencase/anaconda3/envs/jax/lib/python3.9/site-packages/dcargs/_cli.py", line 110, in cli
    out = _cli_impl(
  File "/home/mbenencase/anaconda3/envs/jax/lib/python3.9/site-packages/dcargs/_cli.py", line 266, in _cli_impl
    out, consumed_keywords = _calling.call_from_args(
  File "/home/mbenencase/anaconda3/envs/jax/lib/python3.9/site-packages/dcargs/_calling.py", line 200, in call_from_args
    return unwrapped_f(*args, **kwargs), consumed_keywords  # type: ignore
  File "/home/mbenencase/projects/jaxlie/se3_optimization.py", line 236, in main
    run_experiment(algorithm, learning_rate, train_steps),
  File "/home/mbenencase/projects/jaxlie/se3_optimization.py", line 199, in run_experiment
    state = State.initialize(algorithm, learning_rate)
  File "/home/mbenencase/projects/jaxlie/se3_optimization.py", line 127, in initialize
    optimizer_state = optimizer.init(jaxlie.manifold.zero_tangents(params))
AttributeError: module 'jaxlie.manifold' has no attribute 'zero_tangents'
```

---

My system versions

- jax = 0.3.15
- jax-dataclasses = 1.4.3
- jaxlib = 0.3.15
- jaxlie = 1.2.10
- optax = 0.1.3
- Python = 3.9.12
- Ubuntu = 20.04 (LTS)

I installed all jax related packages with `pip` in a conda environment.

**Comment by brentyi** [comment]
Thanks for flagging! The PyPI version was pretty out-of-date. I just did a release, can you see if that fixes your issue?
